// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	gocloak "github.com/Nerzal/gocloak/v13"

	mock "github.com/stretchr/testify/mock"
)

// IKeycloakService is an autogenerated mock type for the IKeycloakService type
type IKeycloakService struct {
	mock.Mock
}

// CreateToken provides a mock function with given fields: ctx
func (_m *IKeycloakService) CreateToken(ctx context.Context) (string, error) {
	ret := _m.Called(ctx)

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (string, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateUser provides a mock function with given fields: ctx, token, role, user
func (_m *IKeycloakService) CreateUser(ctx context.Context, token string, role *gocloak.Role, user gocloak.User) (string, error) {
	ret := _m.Called(ctx, token, role, user)

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *gocloak.Role, gocloak.User) (string, error)); ok {
		return rf(ctx, token, role, user)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *gocloak.Role, gocloak.User) string); ok {
		r0 = rf(ctx, token, role, user)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *gocloak.Role, gocloak.User) error); ok {
		r1 = rf(ctx, token, role, user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteUserByID provides a mock function with given fields: ctx, token, userID
func (_m *IKeycloakService) DeleteUserByID(ctx context.Context, token string, userID string) error {
	ret := _m.Called(ctx, token, userID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, token, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAllUsers provides a mock function with given fields: ctx, token
func (_m *IKeycloakService) GetAllUsers(ctx context.Context, token string) ([]*gocloak.User, error) {
	ret := _m.Called(ctx, token)

	var r0 []*gocloak.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*gocloak.User, error)); ok {
		return rf(ctx, token)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*gocloak.User); ok {
		r0 = rf(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*gocloak.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRoleByID provides a mock function with given fields: ctx, token, roleID
func (_m *IKeycloakService) GetRoleByID(ctx context.Context, token string, roleID string) (*gocloak.Role, error) {
	ret := _m.Called(ctx, token, roleID)

	var r0 *gocloak.Role
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*gocloak.Role, error)); ok {
		return rf(ctx, token, roleID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *gocloak.Role); ok {
		r0 = rf(ctx, token, roleID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gocloak.Role)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, token, roleID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserByID provides a mock function with given fields: ctx, token, userID
func (_m *IKeycloakService) GetUserByID(ctx context.Context, token string, userID string) (*gocloak.User, error) {
	ret := _m.Called(ctx, token, userID)

	var r0 *gocloak.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*gocloak.User, error)); ok {
		return rf(ctx, token, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *gocloak.User); ok {
		r0 = rf(ctx, token, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gocloak.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, token, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserByNickName provides a mock function with given fields: ctx, token, nickName
func (_m *IKeycloakService) GetUserByNickName(ctx context.Context, token string, nickName string) (*gocloak.User, error) {
	ret := _m.Called(ctx, token, nickName)

	var r0 *gocloak.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*gocloak.User, error)); ok {
		return rf(ctx, token, nickName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *gocloak.User); ok {
		r0 = rf(ctx, token, nickName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gocloak.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, token, nickName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IsValidToken provides a mock function with given fields: ctx, accessToken
func (_m *IKeycloakService) IsValidToken(ctx context.Context, accessToken string) (bool, error) {
	ret := _m.Called(ctx, accessToken)

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, accessToken)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, accessToken)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, accessToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Login provides a mock function with given fields: ctx, user, password
func (_m *IKeycloakService) Login(ctx context.Context, user string, password string) (*gocloak.JWT, error) {
	ret := _m.Called(ctx, user, password)

	var r0 *gocloak.JWT
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*gocloak.JWT, error)); ok {
		return rf(ctx, user, password)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *gocloak.JWT); ok {
		r0 = rf(ctx, user, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gocloak.JWT)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, user, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Logout provides a mock function with given fields: ctx, refreshToken
func (_m *IKeycloakService) Logout(ctx context.Context, refreshToken string) error {
	ret := _m.Called(ctx, refreshToken)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, refreshToken)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewIKeycloakService creates a new instance of IKeycloakService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIKeycloakService(t interface {
	mock.TestingT
	Cleanup(func())
}) *IKeycloakService {
	mock := &IKeycloakService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
