// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"

	mock "github.com/stretchr/testify/mock"
)

// IMetricMiddleWare is an autogenerated mock type for the IMetricMiddleWare type
type IMetricMiddleWare struct {
	mock.Mock
}

// DefaultMetrics provides a mock function with given fields: c
func (_m *IMetricMiddleWare) DefaultMetrics(c *gin.Context) {
	_m.Called(c)
}

// PersonalMetrics provides a mock function with given fields: c
func (_m *IMetricMiddleWare) PersonalMetrics(c *gin.Context) {
	_m.Called(c)
}

// NewIMetricMiddleWare creates a new instance of IMetricMiddleWare. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIMetricMiddleWare(t interface {
	mock.TestingT
	Cleanup(func())
}) *IMetricMiddleWare {
	mock := &IMetricMiddleWare{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
