// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// IRestfulService is an autogenerated mock type for the IRestfulService type
type IRestfulService struct {
	mock.Mock
}

// Get provides a mock function with given fields: ctx, url, timeOut
func (_m *IRestfulService) Get(ctx context.Context, url string, timeOut string) ([]byte, error) {
	ret := _m.Called(ctx, url, timeOut)

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) ([]byte, error)); ok {
		return rf(ctx, url, timeOut)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) []byte); ok {
		r0 = rf(ctx, url, timeOut)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, url, timeOut)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIRestfulService creates a new instance of IRestfulService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIRestfulService(t interface {
	mock.TestingT
	Cleanup(func())
}) *IRestfulService {
	mock := &IRestfulService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
