// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	request "cow_sso/api/dto/request"

	mock "github.com/stretchr/testify/mock"

	response "cow_sso/api/dto/response"
)

// IUserService is an autogenerated mock type for the IUserService type
type IUserService struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, userRequest
func (_m *IUserService) Create(ctx context.Context, userRequest request.UserRequest) error {
	ret := _m.Called(ctx, userRequest)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, request.UserRequest) error); ok {
		r0 = rf(ctx, userRequest)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, nickName
func (_m *IUserService) Delete(ctx context.Context, nickName string) (string, error) {
	ret := _m.Called(ctx, nickName)

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, nickName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, nickName)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, nickName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAll provides a mock function with given fields: ctx
func (_m *IUserService) GetAll(ctx context.Context) ([]response.UserResponse, error) {
	ret := _m.Called(ctx)

	var r0 []response.UserResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]response.UserResponse, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []response.UserResponse); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]response.UserResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByNickName provides a mock function with given fields: ctx, nickName
func (_m *IUserService) GetByNickName(ctx context.Context, nickName string) (response.UserResponse, error) {
	ret := _m.Called(ctx, nickName)

	var r0 response.UserResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (response.UserResponse, error)); ok {
		return rf(ctx, nickName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) response.UserResponse); ok {
		r0 = rf(ctx, nickName)
	} else {
		r0 = ret.Get(0).(response.UserResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, nickName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIUserService creates a new instance of IUserService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIUserService(t interface {
	mock.TestingT
	Cleanup(func())
}) *IUserService {
	mock := &IUserService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
